services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DBNAME=course_db

volumes:
  mongo-data:
